/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated/app.sales'
import { Route as AuthenticatedAppMeetingsRouteImport } from './routes/_authenticated/app.meetings'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppProspectsIndexRouteImport } from './routes/_authenticated/app.prospects.index'
import { Route as AuthenticatedAppProductsIndexRouteImport } from './routes/_authenticated/app.products.index'
import { Route as AuthenticatedAppLearningIndexRouteImport } from './routes/_authenticated/app.learning.index'
import { Route as AuthenticatedAppSettingsUsersRouteImport } from './routes/_authenticated/app.settings.users'
import { Route as AuthenticatedAppSettingsMyCompanyRouteImport } from './routes/_authenticated/app.settings.my-company'
import { Route as AuthenticatedAppProspectsNewRouteImport } from './routes/_authenticated/app.prospects.new'
import { Route as AuthenticatedAppProspectsIdRouteImport } from './routes/_authenticated/app.prospects.$id'
import { Route as AuthenticatedAppProductsNewRouteImport } from './routes/_authenticated/app.products.new'
import { Route as AuthenticatedAppProductsIdRouteImport } from './routes/_authenticated/app.products.$id'
import { Route as AuthenticatedAppLearningNewRouteImport } from './routes/_authenticated/app.learning.new'
import { Route as AuthenticatedAppLearningIdRouteImport } from './routes/_authenticated/app.learning.$id'
import { Route as AuthenticatedAppLeadsIdRouteImport } from './routes/_authenticated/app.leads.$id'
import { Route as AuthenticatedAppProspectsIdCompetitorSlugRouteImport } from './routes/_authenticated/app.prospects.$id.competitor.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMeetingsRoute =
  AuthenticatedAppMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProspectsIndexRoute =
  AuthenticatedAppProspectsIndexRouteImport.update({
    id: '/prospects/',
    path: '/prospects/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsIndexRoute =
  AuthenticatedAppProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearningIndexRoute =
  AuthenticatedAppLearningIndexRouteImport.update({
    id: '/learning/',
    path: '/learning/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsUsersRoute =
  AuthenticatedAppSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsMyCompanyRoute =
  AuthenticatedAppSettingsMyCompanyRouteImport.update({
    id: '/my-company',
    path: '/my-company',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppProspectsNewRoute =
  AuthenticatedAppProspectsNewRouteImport.update({
    id: '/prospects/new',
    path: '/prospects/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProspectsIdRoute =
  AuthenticatedAppProspectsIdRouteImport.update({
    id: '/prospects/$id',
    path: '/prospects/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsNewRoute =
  AuthenticatedAppProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsIdRoute =
  AuthenticatedAppProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearningNewRoute =
  AuthenticatedAppLearningNewRouteImport.update({
    id: '/learning/new',
    path: '/learning/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearningIdRoute =
  AuthenticatedAppLearningIdRouteImport.update({
    id: '/learning/$id',
    path: '/learning/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsIdRoute = AuthenticatedAppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppLeadsRoute,
} as any)
const AuthenticatedAppProspectsIdCompetitorSlugRoute =
  AuthenticatedAppProspectsIdCompetitorSlugRouteImport.update({
    id: '/competitor/$slug',
    path: '/competitor/$slug',
    getParentRoute: () => AuthenticatedAppProspectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/app/learning/$id': typeof AuthenticatedAppLearningIdRoute
  '/app/learning/new': typeof AuthenticatedAppLearningNewRoute
  '/app/products/$id': typeof AuthenticatedAppProductsIdRoute
  '/app/products/new': typeof AuthenticatedAppProductsNewRoute
  '/app/prospects/$id': typeof AuthenticatedAppProspectsIdRouteWithChildren
  '/app/prospects/new': typeof AuthenticatedAppProspectsNewRoute
  '/app/settings/my-company': typeof AuthenticatedAppSettingsMyCompanyRoute
  '/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
  '/app/learning/': typeof AuthenticatedAppLearningIndexRoute
  '/app/products/': typeof AuthenticatedAppProductsIndexRoute
  '/app/prospects/': typeof AuthenticatedAppProspectsIndexRoute
  '/app/prospects/$id/competitor/$slug': typeof AuthenticatedAppProspectsIdCompetitorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/app/learning/$id': typeof AuthenticatedAppLearningIdRoute
  '/app/learning/new': typeof AuthenticatedAppLearningNewRoute
  '/app/products/$id': typeof AuthenticatedAppProductsIdRoute
  '/app/products/new': typeof AuthenticatedAppProductsNewRoute
  '/app/prospects/$id': typeof AuthenticatedAppProspectsIdRouteWithChildren
  '/app/prospects/new': typeof AuthenticatedAppProspectsNewRoute
  '/app/settings/my-company': typeof AuthenticatedAppSettingsMyCompanyRoute
  '/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
  '/app/learning': typeof AuthenticatedAppLearningIndexRoute
  '/app/products': typeof AuthenticatedAppProductsIndexRoute
  '/app/prospects': typeof AuthenticatedAppProspectsIndexRoute
  '/app/prospects/$id/competitor/$slug': typeof AuthenticatedAppProspectsIdCompetitorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/_authenticated/app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/leads/$id': typeof AuthenticatedAppLeadsIdRoute
  '/_authenticated/app/learning/$id': typeof AuthenticatedAppLearningIdRoute
  '/_authenticated/app/learning/new': typeof AuthenticatedAppLearningNewRoute
  '/_authenticated/app/products/$id': typeof AuthenticatedAppProductsIdRoute
  '/_authenticated/app/products/new': typeof AuthenticatedAppProductsNewRoute
  '/_authenticated/app/prospects/$id': typeof AuthenticatedAppProspectsIdRouteWithChildren
  '/_authenticated/app/prospects/new': typeof AuthenticatedAppProspectsNewRoute
  '/_authenticated/app/settings/my-company': typeof AuthenticatedAppSettingsMyCompanyRoute
  '/_authenticated/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
  '/_authenticated/app/learning/': typeof AuthenticatedAppLearningIndexRoute
  '/_authenticated/app/products/': typeof AuthenticatedAppProductsIndexRoute
  '/_authenticated/app/prospects/': typeof AuthenticatedAppProspectsIndexRoute
  '/_authenticated/app/prospects/$id/competitor/$slug': typeof AuthenticatedAppProspectsIdCompetitorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app'
    | '/app/leads'
    | '/app/meetings'
    | '/app/sales'
    | '/app/settings'
    | '/app/'
    | '/app/leads/$id'
    | '/app/learning/$id'
    | '/app/learning/new'
    | '/app/products/$id'
    | '/app/products/new'
    | '/app/prospects/$id'
    | '/app/prospects/new'
    | '/app/settings/my-company'
    | '/app/settings/users'
    | '/app/learning/'
    | '/app/products/'
    | '/app/prospects/'
    | '/app/prospects/$id/competitor/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/leads'
    | '/app/meetings'
    | '/app/sales'
    | '/app/settings'
    | '/app'
    | '/app/leads/$id'
    | '/app/learning/$id'
    | '/app/learning/new'
    | '/app/products/$id'
    | '/app/products/new'
    | '/app/prospects/$id'
    | '/app/prospects/new'
    | '/app/settings/my-company'
    | '/app/settings/users'
    | '/app/learning'
    | '/app/products'
    | '/app/prospects'
    | '/app/prospects/$id/competitor/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/meetings'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/leads/$id'
    | '/_authenticated/app/learning/$id'
    | '/_authenticated/app/learning/new'
    | '/_authenticated/app/products/$id'
    | '/_authenticated/app/products/new'
    | '/_authenticated/app/prospects/$id'
    | '/_authenticated/app/prospects/new'
    | '/_authenticated/app/settings/my-company'
    | '/_authenticated/app/settings/users'
    | '/_authenticated/app/learning/'
    | '/_authenticated/app/products/'
    | '/_authenticated/app/prospects/'
    | '/_authenticated/app/prospects/$id/competitor/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/meetings': {
      id: '/_authenticated/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AuthenticatedAppMeetingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prospects/': {
      id: '/_authenticated/app/prospects/'
      path: '/prospects'
      fullPath: '/app/prospects/'
      preLoaderRoute: typeof AuthenticatedAppProspectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products/': {
      id: '/_authenticated/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AuthenticatedAppProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learning/': {
      id: '/_authenticated/app/learning/'
      path: '/learning'
      fullPath: '/app/learning/'
      preLoaderRoute: typeof AuthenticatedAppLearningIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/users': {
      id: '/_authenticated/app/settings/users'
      path: '/users'
      fullPath: '/app/settings/users'
      preLoaderRoute: typeof AuthenticatedAppSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/my-company': {
      id: '/_authenticated/app/settings/my-company'
      path: '/my-company'
      fullPath: '/app/settings/my-company'
      preLoaderRoute: typeof AuthenticatedAppSettingsMyCompanyRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/prospects/new': {
      id: '/_authenticated/app/prospects/new'
      path: '/prospects/new'
      fullPath: '/app/prospects/new'
      preLoaderRoute: typeof AuthenticatedAppProspectsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prospects/$id': {
      id: '/_authenticated/app/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/app/prospects/$id'
      preLoaderRoute: typeof AuthenticatedAppProspectsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products/new': {
      id: '/_authenticated/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AuthenticatedAppProductsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products/$id': {
      id: '/_authenticated/app/products/$id'
      path: '/products/$id'
      fullPath: '/app/products/$id'
      preLoaderRoute: typeof AuthenticatedAppProductsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learning/new': {
      id: '/_authenticated/app/learning/new'
      path: '/learning/new'
      fullPath: '/app/learning/new'
      preLoaderRoute: typeof AuthenticatedAppLearningNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learning/$id': {
      id: '/_authenticated/app/learning/$id'
      path: '/learning/$id'
      fullPath: '/app/learning/$id'
      preLoaderRoute: typeof AuthenticatedAppLearningIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads/$id': {
      id: '/_authenticated/app/leads/$id'
      path: '/$id'
      fullPath: '/app/leads/$id'
      preLoaderRoute: typeof AuthenticatedAppLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAppLeadsRoute
    }
    '/_authenticated/app/prospects/$id/competitor/$slug': {
      id: '/_authenticated/app/prospects/$id/competitor/$slug'
      path: '/competitor/$slug'
      fullPath: '/app/prospects/$id/competitor/$slug'
      preLoaderRoute: typeof AuthenticatedAppProspectsIdCompetitorSlugRouteImport
      parentRoute: typeof AuthenticatedAppProspectsIdRoute
    }
  }
}

interface AuthenticatedAppLeadsRouteChildren {
  AuthenticatedAppLeadsIdRoute: typeof AuthenticatedAppLeadsIdRoute
}

const AuthenticatedAppLeadsRouteChildren: AuthenticatedAppLeadsRouteChildren = {
  AuthenticatedAppLeadsIdRoute: AuthenticatedAppLeadsIdRoute,
}

const AuthenticatedAppLeadsRouteWithChildren =
  AuthenticatedAppLeadsRoute._addFileChildren(
    AuthenticatedAppLeadsRouteChildren,
  )

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsMyCompanyRoute: typeof AuthenticatedAppSettingsMyCompanyRoute
  AuthenticatedAppSettingsUsersRoute: typeof AuthenticatedAppSettingsUsersRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsMyCompanyRoute:
      AuthenticatedAppSettingsMyCompanyRoute,
    AuthenticatedAppSettingsUsersRoute: AuthenticatedAppSettingsUsersRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppProspectsIdRouteChildren {
  AuthenticatedAppProspectsIdCompetitorSlugRoute: typeof AuthenticatedAppProspectsIdCompetitorSlugRoute
}

const AuthenticatedAppProspectsIdRouteChildren: AuthenticatedAppProspectsIdRouteChildren =
  {
    AuthenticatedAppProspectsIdCompetitorSlugRoute:
      AuthenticatedAppProspectsIdCompetitorSlugRoute,
  }

const AuthenticatedAppProspectsIdRouteWithChildren =
  AuthenticatedAppProspectsIdRoute._addFileChildren(
    AuthenticatedAppProspectsIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRouteWithChildren
  AuthenticatedAppMeetingsRoute: typeof AuthenticatedAppMeetingsRoute
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppLearningIdRoute: typeof AuthenticatedAppLearningIdRoute
  AuthenticatedAppLearningNewRoute: typeof AuthenticatedAppLearningNewRoute
  AuthenticatedAppProductsIdRoute: typeof AuthenticatedAppProductsIdRoute
  AuthenticatedAppProductsNewRoute: typeof AuthenticatedAppProductsNewRoute
  AuthenticatedAppProspectsIdRoute: typeof AuthenticatedAppProspectsIdRouteWithChildren
  AuthenticatedAppProspectsNewRoute: typeof AuthenticatedAppProspectsNewRoute
  AuthenticatedAppLearningIndexRoute: typeof AuthenticatedAppLearningIndexRoute
  AuthenticatedAppProductsIndexRoute: typeof AuthenticatedAppProductsIndexRoute
  AuthenticatedAppProspectsIndexRoute: typeof AuthenticatedAppProspectsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRouteWithChildren,
  AuthenticatedAppMeetingsRoute: AuthenticatedAppMeetingsRoute,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppLearningIdRoute: AuthenticatedAppLearningIdRoute,
  AuthenticatedAppLearningNewRoute: AuthenticatedAppLearningNewRoute,
  AuthenticatedAppProductsIdRoute: AuthenticatedAppProductsIdRoute,
  AuthenticatedAppProductsNewRoute: AuthenticatedAppProductsNewRoute,
  AuthenticatedAppProspectsIdRoute:
    AuthenticatedAppProspectsIdRouteWithChildren,
  AuthenticatedAppProspectsNewRoute: AuthenticatedAppProspectsNewRoute,
  AuthenticatedAppLearningIndexRoute: AuthenticatedAppLearningIndexRoute,
  AuthenticatedAppProductsIndexRoute: AuthenticatedAppProductsIndexRoute,
  AuthenticatedAppProspectsIndexRoute: AuthenticatedAppProspectsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
